### PR TITLE
Added information related to viaq_index_name field

### PR DESCRIPTION
**Pull request by mijicherian**

### CODE REVIEW

**Comment by richm** [comment]
@lukas-vlcek any idea why the test failed?

**Comment by lukas-vlcek** [comment]
It fails because you are introducing a new field `viaq_index_name`. When the test "wget"s released index template (from Github) and compares it with newly generated index template it does not find the field `viaq_index_name` in released index template. It is found only in the newly generated index template. And this is considered an issue ([diff](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L226) is not empty).

You can navigate to [failed test details](https://travis-ci.org/ViaQ/elasticsearch-templates/builds/605615840?utm_source=github_status&utm_medium=notification) and search for `viaq_index_name` string. It will give you some clue about this.

Anyway, in cases like this it is needed to introduce an exception for this field into the test and remove this field from generated model. This means removing relevant part of JSON document.

How to do it:

The line where the new (fresh) index templated is generated in the test is [here](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L121). Right after this the generated model is modified depending on which released model we want to compare it with (i.e. target ES version). Given, this field has been introduced just now I think we will need to remove this field for all target ES versions (the field is not part of any released model at this moment).

So I would recommend adding a new method to remove relevant mapping [like this](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L80-L88) and call it in the end of each if-then blocks: [here](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L158), [here](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L160) and [here](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_templates_test.py#L164).

I can do it if you want.

Later, when we decide which model versions this new field will be propagated to and after relevant releases are made we will remove the exception from test for those versions.

**Comment by lukas-vlcek** [comment]
Also something similar will have to be fixed for [index patterns test somewhere here](https://github.com/ViaQ/elasticsearch-templates/blob/0e3ccafd4ff5c9300ec25421c70b2cb105aaacb5/scripts/compare_against_released_patterns_test.py#L129).

But let's fix the index template test first.

**Comment by mijicherian** [comment]
Can you please let me know the Licencing details of this repository?

**Comment by lukas-vlcek** [comment]
@mijicherian Good point, seems we forgot to add LICENSE details into this repo. I am sure it should have been AL2 but let me check if we can add it retrospectively.

**Comment by richm** [comment]
Yes, we can add it retroactively

**Pull request merged**
