### PR TITLE
add support for viaq_msg_id

### PR DESCRIPTION
**Pull request by richm**
@jcantrill

### CODE REVIEW

**Review by jcantrill — APPROVED** [review]

**Comment by richm** [comment]
@lukas-vlcek any idea why these tests are failing?

**Comment by lukas-vlcek** [comment]
@richm You introduced a new field `viaq_msg_id` into the model and this means that tests that compare released model (downloaded from <https://github.com/ViaQ/elasticsearch-templates/releases>) to the latest generated model do not pass. I understand that the test error output is quite cryptic but you can see for example [here](https://travis-ci.org/ViaQ/elasticsearch-templates/builds/349050622#L487) that it gives us a hit like:

```
  self.assertEqual(released_index_template, generated_index_template)
AssertionError:
'{"al[17332 chars]ing"}}}},"order": 20,"settings": {"index.refre[54 chars]-*"}'
!=
'{"al[17332 chars]ing"},"viaq_msg_id": {"doc_values": true,"inde[131 chars]-*"}'
```
_(... did I really say "hit"?)_

This is nothing unexpected when model is changed that tests comparing against released model fail. 

You will need to add an exception for this new field into both tests [`scripts/compare_against_released_patterns_test.py`](https://github.com/ViaQ/elasticsearch-templates/blob/master/scripts/compare_against_released_patterns_test.py) and [`scripts/compare_against_released_templates_test.py`](https://github.com/ViaQ/elasticsearch-templates/blob/master/scripts/compare_against_released_templates_test.py).
By exception in this case I mean you simply need to remove this field from generated data as it is not part of released model.

In each test find a place where the **generated data** is fixed (see [`scripts/compare_against_released_patterns_test.py#L91-L96`](https://github.com/ViaQ/elasticsearch-templates/blob/master/scripts/compare_against_released_patterns_test.py#L91-L96) and [`scripts/compare_against_released_templates_test.py#L55-L66`](https://github.com/ViaQ/elasticsearch-templates/blob/master/scripts/compare_against_released_templates_test.py#L55-L66)) and remove the field.

I usually try to add a link to relevant github issue into comment.

There is a document how to [run tests](https://github.com/ViaQ/elasticsearch-templates/blob/master/scripts/UnitTestingHowTo.md) locally. Basically, the travis script currently runs:
```
  - cd scripts
  - python -m unittest -v generate_template_test
  - python -m unittest -v compare_against_released_templates_test
  - python -m unittest -v compare_against_released_patterns_test
```

**Comment by richm** [comment]
@lukas-vlcek like this?

**Comment by lukas-vlcek** [comment]
@richm yup! And tests are passing :-)
We will be able to remove a lot of these fixes/exceptions in tests once we start testing against 0.0.13 release model (except this new field because it is not part of 0.0.13, it will be part of 0.0.13.1 or later).

**Pull request merged**
