### PR TITLE
add new systemd fields

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
would like to get these in before the next release

**Comment by lukas-vlcek** [comment]
@richm sure, I will fix tests for this

**Comment by lukas-vlcek** [comment]
@richm I think your branch [`new-fields`](https://github.com/richm/elasticsearch-templates/tree/new-fields) is missing some commits compared to upstream master. Do you think you can do rebase first and force push to your branch again?

It has older version of test files and I need to fix failing tests for which I need updated version of testing files.

**Review by lukas-vlcek — APPROVED** [review]
LGTM

**Pull request merged**
