### PR TITLE
Documentation generation for fields.

### PR DESCRIPTION
**Pull request by t0ffel**
Added asciidoc for openshift fields.
New make target 'docs' to generate docs.

fyi @jcantrill @portante 

Please provide your comments/what else is needed

### CODE REVIEW

**Comment by richm** [comment]
Nice!

The `level` docs are not formatted correctly:
```
Logging level as provided by: rsyslog(severitytext property), python's logging module, etc. Possible values are as listed here: http://sourceware.org/git/?p=glibc.git;a=blob;f=misc/sys/syslog.h;h=ee01478c4b19a954426a96448577c5a76e6647c0;hb=HEAD#l74 plus trace That is: alert crit debug emerg err info notice trace warning Note that `trace` isn't in the syslog.h list but many applications use it `trace` should be considered the highest (most verbose) level, higher than `debug` `error` should be converted to `err` `panic` should be converted to `emerg` `warn` should be converted to `warning` Numeric values from syslog/journal PRIORITY can usually be mapped using the priority values as listed here: http://sourceware.org/git/?p=glibc.git;a=blob;f=misc/sys/syslog.h;h=ee01478c4b19a954426a96448577c5a76e6647c0;hb=HEAD#l51 That is, 0 -> emerg, 1 -> alert, ..., 7 -> debug Log levels/priorities from other logging systems should be mapped to the nearest match For example, from python logging: https://docs.python.org/2.7/library/logging.html#logging-levels CRITICAL -> crit, ERROR -> err, ...., DEBUG -> debug
```
Is there some way to preserve the formatting in the namespace file?  Or is the `description` for `level` formatted incorrectly in the namespace file?

**Comment by richm** [comment]
http://www.yaml.org/spec/1.2/spec.html#id2793718
`level` should use `|`

**Comment by richm** [comment]
Subfields are indented/headered at the same level as their parent fields.  For example:
```
[[exported-fields-systemd]]
=== systemd Fields
...
[[exported-fields-k]]
=== k Fields

systemd's kernel-specific metadata.
```
Is there some way we can indent these?  I realize that we cannot keep indenting for arbitrary depth of nesting, but can we do at least 3 levels?

For the top level field:
```
[[exported-fields]]
== Exported Fields
```
can we move this up one (to `=` instead of `==`) to "make room" for more subfield indentation?  That means `Exported Fields` is at the Title level, but I think that's ok.

**Comment by richm** [comment]
If that's too much trouble, then just include the name of the parent in the subfield:
```
[[exported-fields-systemd-k]]
=== systemd.k Fields
```
In fact, it may be good to have _all_ references to a field to include the parent field as well.  For example:
```
==== pipeline_metadata.normalizer.original_raw_message
```
because this is how people will use it e.g. in an ES query: `/project.*/_search?q=pipeline_metadata.normalizer.original_raw_message:my original message` or in Kibana.

**Comment by jcantrill** [comment]
This is a great start.  Please make sure to link into the trello card and work with @bmcelvee to get into our official documentation.  @richm is there any way we can link this someplace into the origin-logging-repo?  Thoughts on how to best represent it there?

**Comment by richm** [comment]
@jcantrill I suppose we could check it into origin-aggregated-logging/docs ?

**Comment by t0ffel** [comment]
I've done this - I don't think that I'll have time to do more in the coming week.
```
[[exported-fields-systemd-k]]
=== systemd.k Fields
```

**Review by richm — APPROVED** [review]

**Pull request merged**
