### PR TITLE
allow configuring _source, _all, include_in_all

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
@t0ffel @portante @lukas-vlcek @sradco PTAL

**Comment by lukas-vlcek** [comment]
Was quickly looking at the code changes and I am not sure I get what does this change bring. Is there any "plain english" summary please?
Edit: I see now, the description is in commit comment.

**Comment by lukas-vlcek** [comment]
> The default for all of these is `True`.

I would question why `_all` and `include_in_all` do not default to **false**? Is there any existing use case which relies on `_all` field?

As for ability to disable `_source`, is there any specific motivation for disabling the `_source` except reducing the index size? (Hint: without `_source` it is not possible to reindex the data or get the original data from ES, `_source` can be also useful for ad-hoc scripting in ES queries)

**Comment by richm** [comment]
> I would question why _all and include_in_all do not default to false? Is there any existing use case which relies on _all field?

The default is `true` in previous versions.  I did not want to change that, in case customers are using ad hoc queries like `q=some_term`, which would be broken if I made the default `false`.

> As for ability to disable _source, is there any specific motivation for disabling the _source

Perhaps @sradco can explain.  But anyway, it's there in case someone wants to use it.

**Comment by lukas-vlcek** [comment]
ok, LGTM

**Comment by sradco** [comment]
@richm @lukas-vlcek 
If you look at https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html
you will see that it is recommended to disable _source for metrics.

We want to be able to create searches and dashboards , but it is less interesting for metrics to view the data in the discovery tab.

I'll need to better understand how to use the tags in order for the user to be able to filter easily the data.

This should indeed save disk space.

**Comment by sradco** [comment]
@richm @lukas-vlcek 
If you look at https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html
you will see that it is recommended to disable _source for metrics.

We want to be able to create searches and dashboards , but it is less interesting for metrics to view the data in the discovery tab.

I'll need to better understand how to use the tags in order for the user to be able to filter easily the data.

This should indeed save disk space.

**Comment by lukas-vlcek** [comment]
@sradco Right, for metrics it makes sense. 👍

**Pull request merged**
