### PR TITLE
Updates _default_.yml with message.raw field

### PR DESCRIPTION
**Pull request by sradco**
Added message.raw field

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Is this still required? I wonder what the "raw" field for `message` would be useful for?

**Comment by sradco** [comment]
No. It's not required any more.

--

SHIRLY RADCO

BI SOFTWARE ENGINEER

Red Hat Israel

￼

TRIED. TESTED. TRUSTED.

**Comment by richm** [comment]
I think by default we want the `message` field to be processed as an analyzed `text` field to do substring searching on it.  The only use for a `.raw` subfield would be if you wanted to index it as a `keyword` to do an exact match search on it (not sure why you would want to do that - maybe you have an error message in a log file somewhere, and you want to do an exact match search on it to find that exact same record in Elasticsearch)?

**Comment by meanderix** [comment]
Here's a quote from the [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html):
> It is often useful to index the same field in different ways for different purposes. This is the purpose of multi-fields. For instance, a string field could be mapped as a text field for full-text search, and as a keyword field for sorting or aggregations.

Currently the `message` field is not aggregatable since it does not provide the `raw` multifield mapping. This will completely eliminate a lot of useful features in Kibana, such as visualizations and "significant terms" (which is possible in several other elasticsearch-based log analysis tools).

Additional info:
https://www.elastic.co/blog/strings-are-dead-long-live-strings
https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html#before-enabling-fielddata

**Pull request closed without merging**
