### PR TITLE
Update ovirt.yml

### PR DESCRIPTION
**Pull request by sradco**
Update engine_fqdn and cluster_name to be raw.

@richm Please review my patch.

### CODE REVIEW

**Comment by richm** [comment]
@lukas-vlcek ptal - does this need to be changed for es5?

**Comment by lukas-vlcek** [comment]
@richm Yes, it does. Specifically https://github.com/ViaQ/elasticsearch-templates/issues/73 and https://github.com/ViaQ/elasticsearch-templates/issues/67.

**Comment by richm** [comment]
@lukas-vlcek are your changes for es5 ready to be merged?  If so, @sradco please resubmit once those have merged

**Comment by lukas-vlcek** [comment]
@sradco @richm Is this change going to be needed in ES 5.x based logging only or also in ES 2.x based logging?

**Comment by richm** [comment]
@lukas-vlcek yes - ES5 and ES2

**Comment by richm** [comment]
@sradco please update this PR based on the latest merge to add ES 5 support

**Comment by lukas-vlcek** [comment]
@sradco Please notice that after [upgrade to ES 5.x](https://github.com/ViaQ/elasticsearch-templates/pull/70) all the fields under `ovirt` namespace are `keyword`s now. See: <https://github.com/ViaQ/elasticsearch-templates/blob/12cb6938db6d6069d171502e9e38a97551183338/namespaces/ovirt.yml>

This means there is no need to add `raw` field for any of them.
The index templates for `project.*` and `.operation.*` indices goes like this now:
```json
    "ovirt": {
      "properties": {
        "cluster_name": {
          "doc_values": true,
          "index": true,
          "type": "keyword"
        },
        "engine_fqdn": {
          "doc_values": true,
          "index": true,
          "type": "keyword"
        },
        "entity": {
          "doc_values": true,
          "index": true,
          "type": "keyword"
        },
        "host_id": {
          "doc_values": true,
          "index": true,
          "type": "keyword"
        }
      }
    }
```
Is this ok with you? If yes, I think we can close this PR.

**Comment by lukas-vlcek** [comment]
For completeness the following is how index mappings are looking like for ES 2x (and also in the [released templates 0.0.12](https://github.com/ViaQ/elasticsearch-templates/releases/tag/0.0.12)):

```json
"ovirt": {
 "properties": {
   "cluster_name": {
     "doc_values": true,
     "index": "not_analyzed",
     "type": "string"
   },
   "engine_fqdn": {
     "doc_values": true,
     "index": "not_analyzed",
     "type": "string"
   },
   "entity": {
     "doc_values": true,
     "index": "not_analyzed",
     "type": "string"
   },
   "host_id": {
     "doc_values": true,
     "index": "not_analyzed",
     "type": "string"
   }
 }
}
```

**Pull request closed without merging**
